# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRSzPkHSCrEk3zlU96E-2WihzM0SxQPi
"""

def calcular_imc(peso, altura):
    imc = peso / (altura ** 2)
    return round(imc, 2)

def classificar_imc(imc):
    if imc < 18.5:
        return "Subpeso"
    elif 18.5 <= imc < 25.0:
        return "Peso normal"
    elif 25.0 <= imc < 30.0:
        return "Sobrepeso"
    else:
        return "Obesidade"

peso_aluno = 60.0
altura_aluno = 1.80

imc_aluno = calcular_imc(peso_aluno, altura_aluno)
classificacao_aluno = classificar_imc(imc_aluno)

print(f"IMC calculado: {imc_aluno}")
print(f"Classificação: {classificacao_aluno}")

peso_exemplo = 102.0
altura_exemplo = 1.75

imc_exemplo = calcular_imc(peso_exemplo, altura_exemplo)
classificacao_exemplo = classificar_imc(imc_exemplo)

print(f"\nIMC calculado: {imc_exemplo}")
print(f"Classificação: {classificacao_exemplo}")